### ISSUE TITLE
bladerf_power.py seems to ignore frequency range on command line

### ISSUE THREAD

**Issue by zanco** [staticfloat/bladerf_power#2]
Running this command:

./bladerf_power.py 1670000:1710000:10k -o 30 -w 3 -e 10 -f /home/pe2bz/files/output.csv followed by running heatmap.py gives:
loading
x: 355600, y: 10, z: (-19.590000, 127.080000)
drawing
labeling
saving

after that, a PNG image is saved with dimensions 355600 x 35 pixels.

After zooming out and viewing the left part of the image it shows: 
range 237.50 MHz - 3793.50 MHz

tested the command line with 1670M:1710M gives an heatmap.py error:
ValueError: 3785999999.0 is not in list

Edited the output.csv in openoffice. Looks like the default sample rate is added to the start frequency up to the 3800 MHz limit:
![image](https://cloud.githubusercontent.com/assets/4477734/12007663/80816416-ac0e-11e5-8b4f-495cd0217c18.png)

I am not a python specialist, but I have printed the script and noticed something odd in my opinion at line 264
end_freq = max(start_freq, bladeRF.FREQUENCY_MAX)

Could it be that it should read
end_freq = min(end_freq, bladeRF.FREQUENCY_MAX)

Because now I think bladerffrequencymax is always choosen as end_freq.

Will test tomorrow and update issue.

With the change I described above all seems OK now.

![irridium_heatmap](https://cloud.githubusercontent.com/assets/4477734/12009813/647dc3ba-ac89-11e5-9428-685cb72618bf.JPG)

**Comment by staticfloat** [comment]
Yes, you are correct, thank you for this @zanco, I have updated the script.
